spring:
  application:
    name: zuul-proxy
server:
  port: 5555
  servlet:
    context-path: /cloud
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
# http://localhost:5555/cloud[/endpoint/]
zuul:
  routes:
    rest-service: /api/v1/products/**